# DataSource Configuration
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/restcode?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&userLegacyDatetimeCode=false
        username: root
        password: root

# JPA properties
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

# Hibernate Configuration
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type: TRACE

# Server Port
server:
    port: 8085


# Eureka client
Eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
      
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
